### ISSUE TITLE
BufferReader::Read does not block until enough bytes are available, contrary to the comment on Reader::Read

### ISSUE THREAD

**Issue by dneto0** [google/langsvr#4]
Reader::Read promises to block until there are `count` bytes available to read.
https://github.com/google/langsvr/blob/main/include/langsvr/reader.h#L44C43-L44C93 

But BufferReader::Read doesn't do that.
https://github.com/google/langsvr/blob/main/src/buffer_reader.cc#L37

**Comment by dneto0** [comment]
Probably a bad comment?

**Comment by ben-clayton** [comment]
> /// Read reads bytes from the stream, blocking until there are @p count bytes available, **or the**
> /// **end of the stream has been reached.**

`BufferReader` reads from a buffer, so `Read` is correct to read up to the end of the buffer (the "end of the stream").

**Comment by dneto0** [comment]
ah, of course.
